Launderland/Launderland/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

from .views import *


urlpatterns = [
    path('', homepage, name="homepage"),
    path('serveradmin/', admin.site.urls),
    path('accounts/', include('usermodule.urls')),
    path('laundry/', include('laundry.urls')),
    path('staff/', include('staffmodule.urls')),
    path('customer/', include('customermodule.urls')),
    path('change_password_done/', auth_views.PasswordChangeDoneView.as_view(),
         name="password_change_done"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Launderland/customermodule/urls.py
from django.urls import path
from .views import *

app_name = 'customermodule'

urlpatterns = [
    path('list/', customer_list, name="customer_list"),
    path('<int:id>/detail/', customer_details, name="customer_details"),
]

Launderland/laundry/urls.py
from django.urls import path
from .views import *

app_name = 'laundry'

urlpatterns = [
    # * Dashboard
    path('', laundry, name='laundry'),
    # * fetching sub_service from service while booking (ajax)
    path('sub_service/', sub_service, name='sub_service'),
    # * Customer Booking Details
    path('order/', Bookings, name='booking'),
    path('myorders/', Mybookings, name='mybooking'),
    path('myorders/<int:id>/', Booking_details, name='booking_details'),
    # * Customer Payment Details
    path('payments/', payment_list, name='payment'),
    # * Staff Booking Details
    path('staff_all_order/', staff_all_booking, name='staff_all_booking'),
    path('staff_all_order/<int:id>/edit',
         staff_booking_edit, name='staff_booking_edit'),
]

Launderland/staffmodule/urls.py
from django.urls import path
from .views import *

app_name = 'staffmodule'

urlpatterns = [
    #  ? SERVICES
    path('services/', service_view, name="service"),
    path('services/<int:id>/edit/', service_edit, name="service_edit"),
    path('services/<int:id>/delete/', service_delete, name="service_delete"),
    #  ? SUBSERVICES
    path('services/<int:id>/subservices/',
         sub_service_view, name="subservices"),
    path('subservices/<int:id>/edit/',
         sub_service_edit, name="sub_service_edit"),
    path('subservices/<int:id>/delete/',
         sub_service_delete, name="sub_service_delete"),
    #  ? STAFF
    path('list/', staff_list, name="staff_list"),
    path('<int:id>/detail/', staff_details, name="staff_details"),
]

Launderland/usermodule/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'usermodule'

urlpatterns = [
    path('signup/', customer_signup, name='signup'),
    path('signin/', account_signin, name='signin'),
    path('signout/', account_signout, name='signout'),
    path('myaccount/', account_profile, name='myaccount'),
    path('staff/signup/', staff_signup, name='signup_staff'),
    path('change_password/', auth_views.PasswordChangeView.as_view(),
         name="change_password"),
]

Launderland/laundry/models.py
from django.db import models
from usermodule.models import User
from staffmodule.models import *


class Booking(models.Model):
    cust_id = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="cid")
    assigned_staff = models.ForeignKey(User, on_delete=models.CASCADE)
    services = models.ForeignKey(Service, on_delete=models.CASCADE)
    sub_service = models.ForeignKey(
        Subservice, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    amount = models.FloatField(default=0)
    delivery_choice = (('pickup', 'Pickup (Self)'), ('door-step', 'Door Step'))
    delivery_type = models.CharField(choices=delivery_choice, max_length=30)
    status_choice = (('New', 'New'), ('pending', 'Pending'), ('cleaning', 'Cleaning'), ('pickedup', 'Picked Up'), ('canceled', 'Canceled'),
                     ('ready', 'Ready'), ('delivered', 'Delivered'))
    status = models.CharField(max_length=20, choices=status_choice,
                              default=status_choice[0][0])
    booked_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Booking'
        verbose_name_plural = 'Bookings'

    def __str__(self):
        return self.cust_id.last_name + ", " + self.cust_id.first_name


class Payment(models.Model):
    cust_id = models.ForeignKey(
        User, on_delete=models.CASCADE)
    booking_id = models.ForeignKey(Booking, on_delete=models.CASCADE)
    payment_mode_choice = (('cash', 'Cash'),
                           ('online', 'Online'))
    payment_mode = models.CharField(
        max_length=25, choices=payment_mode_choice, default=payment_mode_choice[0][0])
    paid_date = models.DateTimeField(auto_now_add=True)
    paid_amount = models.FloatField(null=True, blank=True)
    status_choice = (('paid', 'Paid'),
                     ('not_paid', 'Not Paid'))
    status = models.CharField(
        max_length=10, choices=status_choice, default=status_choice[1][0])

    class Meta:
        verbose_name = 'Payment'
        verbose_name_plural = 'Payments'

Launderland/laundry/forms.py
from django import forms

from staffmodule.models import *
from .models import *


class BookingForm(forms.ModelForm):

    class Meta:
        model = Booking
        fields = ['services', 'sub_service', 'quantity', 'delivery_type']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['services'].label = "Select your service"
        self.fields['sub_service'].label = "What mode do you prefer"
        self.fields['quantity'].label = "How many dress(es) will it be?"
        self.fields['delivery_type'].label = "Delivery Type"

        if 'services' in self.data:
            try:
                service = int(self.data.get('services'))
                self.fields['sub_service'].queryset = Subservice.objects.filter(
                    service=service).order_by('sub_service')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['sub_service'].queryset = self.instance.field.sub_service_set.order_by(
                'service')


class UpdateBookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['status']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(UpdateBookingForm, self).__init__(*args, **kwargs)


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['payment_mode']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)
        self.fields['payment_mode'].label = "Mode of Payment :"

Launderland/laundry/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from usermodule.decorators import *
from usermodule.forms import User

from .forms import *


def laundry(request):
    return render(request, 'laundry/laundry.html')


@user_is_customer
def sub_service(request):
    if request.method == "GET":
        service = request.GET.get('service')
        subservice = Subservice.objects.filter(
            service=service).order_by('sub_service')
        context = {'sub_service': subservice}
        return render(request, 'laundry/sub_service.html', context)


@user_is_customer
def Bookings(request):
    form = BookingForm(request.POST or None)
    staff_free = User.objects.filter(user_type=2, staff_status=False)
    if form.is_valid():
        if staff_free:
            quantity = request.POST.get('quantity')
            price_id = request.POST.get('sub_service')
            price = Subservice.objects.get(id=price_id)
            staff_name = str(staff_free[0].first_name)
            booking_obj = form.save(commit=False)
            booking_obj.amount = price.price * float(quantity)
            booking_obj.cust_id = User.objects.get(id=request.user.id or None)
            booking_obj.assigned_staff = User.objects.get(
                mobile=staff_free[0].mobile)
            booking_obj.save()
            User.objects.filter(mobile=staff_free[0].mobile).update(
                staff_status=True)
            messages.success(
                request, staff_name + " will take care of your laundry")
            return redirect('laundry:mybooking')
        else:
            messages.info(
                request, "Our Staffs are currently busy. Try after some time...")
        return redirect('laundry:laundry')
    return render(request, 'laundry/booking.html', {'form': form})


@user_is_customer
def Mybookings(request):
    bookings = Booking.objects.filter(
        cust_id=request.user.id).order_by('booked_on').reverse()
    return render(request, 'laundry/booking_list.html', {'bookings': bookings})


@login_required
def payment_list(request):
    payments = None
    if request.user.user_type == 1 or request.user.user_type == 2:
        payments = Payment.objects.all().order_by('paid_date').reverse()
    elif request.user.user_type == 3:
        payments = Payment.objects.filter(
            cust_id=request.user.id).order_by('paid_date').reverse()
    return render(request, 'laundry/payment.html', {'payments': payments})


@user_is_customer
def Booking_details(request, id):
    form = PaymentForm(request.POST or None)
    booking = get_object_or_404(Booking, id=id)
    payments = None
    if Payment.objects.filter(booking_id=booking.id).exists():
        payments = Payment.objects.get(booking_id=booking.id)
    elif not Payment.objects.filter(booking_id=booking.id).exists():
        if form.is_valid():
            payment_obj = form.save(commit=False)
            payment_obj.cust_id = User.objects.get(id=request.user.id or None)
            payment_obj.booking_id = Booking.objects.get(id=booking.id)
            payment_obj.paid_amount = booking.amount
            payment_obj.status = "paid"
            payment_obj.save()
            payments = Payment.objects.get(booking_id=booking.id)
    context = {'booking': booking, 'form': form, 'payment': payments}
    return render(request, 'laundry/booking_details.html', context)


@user_is_staff
def staff_all_booking(request):
    bookings = None
    if request.user.user_type == 1:
        bookings = Booking.objects.all().order_by('booked_on').reverse()
    elif request.user.user_type == 2:
        bookings = Booking.objects.filter(
            assigned_staff=request.user.id).order_by('booked_on').reverse()
    return render(request, 'laundry/staff_booking.html', {'booking': bookings})


@user_is_staff
def staff_booking_edit(request, id):
    payments = None
    booking = get_object_or_404(Booking, id=id)
    if Payment.objects.filter(booking_id=booking.id).exists():
        payments = Payment.objects.get(booking_id=booking.id)
    staff_id = booking.assigned_staff.id
    myform = UpdateBookingForm(
        request.POST or None, instance=booking, request=request)
    if myform.is_valid():
        form_obj = myform.save(commit=False)
        if form_obj.status == "delivered" or form_obj.status == "canceled":
            form_obj.save()
            User.objects.filter(id=staff_id).update(
                staff_status=False)
        else:
            form_obj.save()
            User.objects.filter(id=staff_id).update(
                staff_status=True)
        messages.success(
            request, "You have successfully changed Status to \"" + form_obj.status + "\"")
    context = {'form': myform, 'booking': booking, 'payments': payments}
    return render(request, 'laundry/staff_edit_booking.html', context=context)

Launderland/templates/laundry/booking.html
{% extends 'base_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
<title>Launder land | Order Now</title>
{% endblock %}

{% block content %}

<style>
    #div_id_delivery_type,
    #div_id_service_on {
        margin-bottom: 0.5rem;
    }
</style>

<body id="bookings">
    <!-- ? Order FillUp Title -->
    <article class="bg_light_orange_2 container-fluid py-2">
        <section class="pr-md-auto pl-md-5 text-center text-md-left">
            <h3 class="brown mb-0 clamp_size_header">Order Now</h3>
        </section>
    </article>
    <!-- ? Sign Up Form -->
    <article class="container mt-5 px-sm-1">
        <div class="card brown d-flex justify-content-center align-items-center bg-transparent border-0">
            <div class="card-body bg_light_orange_2 rounded">
                <form method="POST" class="needs-validation" novalidate>
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            {{ form.quantity|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.delivery_type|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.services|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.sub_service|as_crispy_field }}
                        </div>
                    </div>
                    <button type="submit"
                        class="btn bg_orange_1 col-lg-2 col-md-2 float-right btn-cust btn-block rounded-pill">Order&nbsp;Now
                    </button>
                </form>
            </div>
        </div>
    </article>

    <script>
        $(document).ready(function () {

            var services = $('#id_services').val();
            if (services != "") {
                $.ajax({
                    url: "{% url 'laundry:sub_service' %}",
                    type: "GET",
                    data: {
                        'service': services
                    },
                    success: function (data) {
                        $('#id_sub_service').html(data);
                    }
                });
            }

            $('#id_services').change(function () {
                var services = $(this).val();
                if (services != "") {
                    $.ajax({
                        url: "{% url 'laundry:sub_service' %}",
                        type: "GET",
                        data: {
                            'service': services
                        },
                        success: function (data) {
                            $('#id_sub_service').html(data);
                        }
                    });
                }
            })

        });
    </script>
</body>


{% endblock %}

Launderland/templates/laundry/booking_list.html
{% extends 'base_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
<title>Launder land | My Orders</title>
{% endblock %}

{% block content %}

<body id="booking">
    <!-- ? My Bookings Title -->
    <article class="bg_light_orange_2 container-fluid py-2">
        <section class="pr-md-auto pl-md-5 text-center text-md-left">
            <h3 class="brown mb-0 clamp_size_header">My Orders</h3>
        </section>
    </article>
    <article class="container-fluid my-2">
        <a href="{% url 'laundry:booking'%}"
            class="btn btn-sm col-lg-1 col-md-2 col-sm-3 brown nav-link btn-cust bg_orange_1 bold rounded-pill my-2">Order&nbsp;Now</a>
        {% if bookings %}
        <div class="row d-flex justify-content-center">
            {% for book in bookings %}
            <section class="card card-cust bg-transparent border-0 m-2" style="width: 18rem;">
                <div class="mx-auto img_body d-flex d-non">
                    <img src="{{ book.assigned_staff.profile_pic.url }}" class="rounded-circle mb-n5 d-non" width="95"
                        alt="{{ book.assigned_staff.first_name }} image" style="z-index:500">
                </div>
                <div class="card-body bg_light_orange_1 text-center brown rounded">
                    <h5 class="card-title pt-5">Order id : {{ book.id }}</h5>
                    <h5 class="card-title">Incharge : {{ book.assigned_staff.first_name }}</h5>
                    <h5 class="card-title">Contact : {{ book.assigned_staff.mobile }}</h5>
                    <a href="{% url 'laundry:booking_details' book.id %}"
                        class="btn btn-cust mt-3 btn-sm bg_orange_1 rounded-pill brown bold">View
                        Details</a>
                </div>
                <div class="card-footer bg_light_orange_1 brown">
                    <span class="">Amount : &#x20B9; {{ book.amount|default:"----" }}</span>
                    <span class="badge float-right rounded-pill mb-0
                    {% if book.status == 'delivered' %}
                    badge-success
                    {% elif book.status == 'ready' %}
                    badge-info
                    {% elif book.status == 'cleaning' %}
                    badge-secondary
                    {% elif book.status == 'pickedup' %}
                    badge-primary
                    {% elif book.status == 'pending' %}
                    badge-warning
                    {% elif book.status == 'canceled' %}
                    badge-danger
                    {% endif %}
                    ">{{ book.status }}</span>
                </div>
            </section>
            {% endfor %}
            {% else %}
            <div class="row d-flex justify-content-center align-items-center" style="height: 50vh;">
                <h4 class="bold brown"> You haven't Ordered anything</h4>
                {% endif %}
            </div>
    </article>

</body>

{% endblock %}

Launderland/templates/laundry/laundry.html
{% extends 'base_layout.html' %}
{% load static %}

{% block title %}
<title>Launder land | Dashboard</title>
{% endblock %}

{% block content %}

<body id="dashboard">
    <!-- ? Title -->
    <article class="bg_light_orange_2 container-fluid py-2">
        <section class="pr-md-auto pl-md-5 text-center text-md-left">
            <h3 class="brown mb-0 clamp_size_header">Dashboard</h3>
        </section>
    </article>
    <article class="container-fluid my-2">
        <div class="row d-flex justify-content-center">
            <!-- * For Customer to Book a laundry Now -->
            {% if user.user_type == 3 %}
            <a href="{% url 'laundry:booking' %}" class="nav-link btn-cust">
                <section class="card card-cust bg_light_orange_1 border-0 m-1" style="width: 18rem;">
                    <div class="card-body bg_light_orange_1 text-center brown rounded">
                        <div class="mx-auto img_body d-flex justify-content-center">
                            <img src="{% static 'images/booking.svg' %}" class="rounded" width="152"
                                alt="{{ staff.first_name }} image" style="z-index:500">
                        </div>
                    </div>
                    <div class="card-footer text-center">
                        <h5 class="card-title brown bold">Order Now</h5>
                    </div>
                </section>
            </a>
            {% endif %}
            {% if user.user_type == 1 or user.user_type ==  2 %}
            <a href="{% url 'laundry:staff_all_booking' %}" class="nav-link btn-cust">
                {% else %}
                <a href="{% url 'laundry:mybooking' %}" class="nav-link btn-cust">
                    {% endif %}
                    <section class="card card-cust bg_light_orange_1 border-0 m-1" style="width: 18rem;">
                        <div class="card-body bg_light_orange_1 text-center brown rounded">
                            <div class="mx-auto img_body d-flex justify-content-center">
                                {% if user.user_type == 1 or user.user_type ==  2 %}
                                <img src="{% static 'images/staff_booking.svg' %}" class="rounded" width="180"
                                    alt="{{ staff.first_name }} image">
                                {% else %}
                                <img src="{% static 'images/customer_booking.svg' %}" class="rounded" width="155"
                                    alt="{{ staff.first_name }} image">
                                {% endif %}
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <h5 class="card-title brown bold">My Orders</h5>
                        </div>
                    </section>
                </a>
                <a href="{% url 'staffmodule:service'%}" class="nav-link btn-cust">
                    <section class="card card-cust bg_light_orange_1 border-0 m-1" style="width: 18rem;">
                        <div class="card-body bg_light_orange_1 text-center brown rounded">
                            <div class="mx-auto img_body d-flex justify-content-center">
                                <img src="{% static 'images/service.svg' %}" class="rounded" width="152"
                                    alt="{{ staff.first_name }} image" style="z-index:500">
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <h5 class="card-title brown bold">Services</h5>
                        </div>
                    </section>
                </a>
                {% if user.user_type == 1 or user.user_type == 2 %}
                <a href="{% url 'staffmodule:staff_list' %}" class="nav-link btn-cust">
                    <section class="card card-cust bg_light_orange_1 border-0 m-1" style="width: 18rem;">
                        <div class="card-body bg_light_orange_1 text-center brown rounded">
                            <div class="mx-auto img_body d-flex justify-content-center">
                                <img src="{% static 'images/staff.svg' %}" class="rounded" width="280"
                                    alt="{{ staff.first_name }} image" style="z-index:500">
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <h5 class="card-title brown bold">Staffs</h5>
                        </div>
                    </section>
                </a>
                {% endif %}
                {% if user.is_authenticated %}
                <a href="{% url 'laundry:payment' %}" class="nav-link btn-cust">
                    <section class="card card-cust bg_light_orange_1 border-0 m-1" style="width: 18rem;">
                        <div class="card-body bg_light_orange_1 text-center brown rounded">
                            <div class="mx-auto img_body d-flex justify-content-center">
                                <img src="{% static 'images/payment.svg' %}" class="rounded" width="270"
                                    alt="{{ staff.first_name }} image" style="z-index:500">
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <h5 class="card-title brown bold">Payment History</h5>
                        </div>
                    </section>
                </a>
                {% endif %}
                {% if user.user_type == 1 %}
                <a href="{% url 'customermodule:customer_list' %}" class="nav-link btn-cust">
                    <section class="card card-cust bg_light_orange_1 border-0 m-1" style="width: 18rem;">
                        <div class="card-body bg_light_orange_1 text-center brown rounded">
                            <div class="mx-auto img_body d-flex justify-content-center">
                                <img src="{% static 'images/customer.svg' %}" class="rounded" width="150"
                                    alt="{{ staff.first_name }} image" style="z-index:500">
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <h5 class="card-title brown bold">Customers</h5>
                        </div>
                    </section>
                </a>
                <a href="{% url 'usermodule:signup_staff' %}" class="nav-link btn-cust">
                    <section class="card card-cust bg_light_orange_1 border-0 m-1" style="width: 18rem;">
                        <div class="card-body bg_light_orange_1 text-center brown rounded">
                            <div class="mx-auto img_body d-flex justify-content-center">
                                <img src="{% static 'images/account.svg' %}" class="rounded" width="150"
                                    alt="{{ staff.first_name }} image" style="z-index:500">
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <h5 class="card-title brown bold">Create Staff account</h5>
                        </div>
                    </section>
                </a>
                {% endif %}
        </div>
    </article>
</body>

{% endblock %}

Launderland/templates/laundry/staff_booking.html
{% extends 'base_layout.html' %}
{% load static %}

{% block title %}
<title>Launder land | Staff Booking</title>
{% endblock %}

{% block content %}

<body id="booking">
    <!-- ? Title -->
    <article class="bg_light_orange_2 container-fluid py-2">
        <section class="pr-md-auto pl-md-5 text-center text-md-left">
            <h3 class="brown mb-0 clamp_size_header">List of Bookings</h3>
        </section>
    </article>
    <!-- ? List of Booking -->
    <article class="container my-2">
        <section class="card shadow-sm my-3 w-100">
            <div class="card-body p-0">
                {% if booking %}
                <div class="table-responsive table-wrapper">
                    <table class="table table-hover mb-0 brown">
                        <!-- * Table Header -->
                        <thead class="bg_light_orange_2">
                            <tr>
                                <th scope="col">No.</th>
                                <th scope="col">Customer</th>
                                <th scope="col">Booking Id</th>
                                {% if user.user_type == 1 %}
                                <th scope="col">Staff</th>
                                {% endif %}
                                <th scope="col">Delivery Type</th>
                                <th scope="col">Amount</th>
                                <th class="text-center" scope="col">Status</th>
                            </tr>
                        </thead>
                        <!-- * Table Content -->
                        <tbody>
                            {% for data in booking %}
                            <tr>
                                {% if forloop %}
                                <th><a class="nav-link p-0 brown btn-cust"
                                        href="{% url 'laundry:staff_booking_edit' data.id %}">{{forloop.counter}}</a>
                                </th>
                                {% endif %}
                                <td>{{ data.cust_id }}</td>
                                <td>{{ data.id }}</td>
                                {% if user.user_type == 1 %}
                                <td>{{ data.assigned_staff }}</td>
                                {% endif %}
                                <td>{{ data.delivery_type }}</td>
                                <td>&#x20B9; {{ data.amount|default:"-----" }}</td>
                                <td class="text-center"><span class="badge rounded-pill mb-0
                                {% if data.status == 'delivered' %}
                                badge-success
                                {% elif data.status == 'ready' %}
                                badge-info
                                {% elif data.status == 'New' %}
                                bg_orange_1 light_orange_1
                                {% elif data.status == 'cleaning' %}
                                badge-secondary
                                {% elif data.status == 'pickedup' %}
                                badge-primary
                                {% elif data.status == 'pending' %}
                                badge-warning
                                {% elif data.status == 'canceled' %}
                                badge-danger
                                {% endif %}
                                ">{{ data.status }}</span></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <div class="row d-flex justify-content-center align-items-center" style="height: 50vh;">
                    <h4 class="bold brown">Looks like you don't have any work</h4>
                </div>
                {% endif %}
            </div>
        </section>
    </article>
</body>

{% endblock %}

Launderland/templates/laundry/sub_service.html
{% for sub in sub_service %}
<option value="{{ sub.pk }}">{{ sub.sub_service }}</option>
{% endfor %}