Launderland/Launderland/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

from .views import *


urlpatterns = [
    path('', homepage, name="homepage"),
    path('serveradmin/', admin.site.urls),
    path('accounts/', include('usermodule.urls')),
    path('laundry/', include('laundry.urls')),
    path('staff/', include('staffmodule.urls')),
    path('customer/', include('customermodule.urls')),
    path('change_password_done/', auth_views.PasswordChangeDoneView.as_view(),
         name="password_change_done"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Launderland/laundry/urls.py
from django.urls import path
from .views import *

app_name = 'laundry'

urlpatterns = [
    # * Dashboard
    path('', laundry, name='laundry'),
    # * fetching sub_service from service while booking (ajax)
    path('sub_service/', sub_service, name='sub_service'),
    # * Customer Booking Details
    path('order/', Bookings, name='booking'),
    path('myorders/', Mybookings, name='mybooking'),
    path('myorders/<int:id>/', Booking_details, name='booking_details'),
    # * Customer Payment Details
    path('payments/', payment_list, name='payment'),
    # * Staff Booking Details
    path('staff_all_order/', staff_all_booking, name='staff_all_booking'),
    path('staff_all_order/<int:id>/edit',
         staff_booking_edit, name='staff_booking_edit'),
]

Launderland/usermodule/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'usermodule'

urlpatterns = [
    path('signup/', customer_signup, name='signup'),
    path('signin/', account_signin, name='signin'),
    path('signout/', account_signout, name='signout'),
    path('myaccount/', account_profile, name='myaccount'),
    path('staff/signup/', staff_signup, name='signup_staff'),
    path('change_password/', auth_views.PasswordChangeView.as_view(),
         name="change_password"),
]

Launderland/usermodule/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, mobile, password, **extra_fields):
        if not mobile:
            raise ValueError('The given mobile must be set')
        # mobile = self.mobile
        user = self.model(mobile=mobile, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, mobile, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(mobile, password, **extra_fields)

    def create_superuser(self, mobile, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(mobile, password, **extra_fields)


class User(AbstractUser):
    username = None
    mobile = models.CharField(unique=True, max_length=10)
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=15)
    profile_pic = models.ImageField(default="profile.png", blank=True)
    gender_choice = (('Male', 'Male'), ('Female', 'Female'),
                     ('Other', 'Other'))
    gender = models.CharField(max_length=7, choices=gender_choice)
    user_type_choice = ((1, 'Owner'), (2, 'Staff'), (3, 'Customer'))
    user_type = models.PositiveSmallIntegerField(
        choices=user_type_choice)
    staff_status = models.BooleanField(default=False)
    address = models.CharField(max_length=100)
    street = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    pincode = models.CharField(max_length=6)
    creation_date = models.DateTimeField(auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'mobile'
    REQUIRED_FIELDS = ['first_name', 'user_type']

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.last_name + ", " + self.first_name

Launderland/usermodule/forms.py
from django import forms
from .models import User


class SignupForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Last Name'}))
    mobile = forms.CharField(widget=forms.NumberInput(
        attrs={'placeholder': 'Mobile Number...'}))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'placeholder': 'yourname@example.com'}))
    address = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Address..'}))
    street = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Street..'}))
    city = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'City...'}))
    state = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'State...'}))
    pincode = forms.CharField(widget=forms.NumberInput(
        attrs={'placeholder': 'Pincode...'}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Must be at least 8+ charaters'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Retype Password'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'mobile',
                  'email', 'gender', 'password', 'confirm_password', 'profile_pic', 'address', 'street', 'city', 'state', 'pincode']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['profile_pic'].label = "Profile Picture"
        self.fields['mobile'].label = "Mobile Number"
        self.fields['email'].label = "Email Address"
        self.fields['first_name'].label = "First Name"
        self.fields['confirm_password'].label = "Confirm Password"
        self.fields['address'].label = "Address"
        self.fields['street'].label = "Street"
        self.fields['city'].label = "City"
        self.fields['state'].label = "State"
        self.fields['pincode'].label = "Pincode"
        self.fields['last_name'].label = "Last Name"
        self.fields['last_name'].required = False

    # validating the email
    def clean_email(self):
        email = self.cleaned_data.get('email').lower()
        return email

    # validating the mobile no
    def clean_mobile(self):
        mobile = self.cleaned_data.get('mobile')
        if not len(mobile) == 10:
            raise forms.ValidationError('Enter a valid Mobile Number')
        if not mobile.isnumeric():
            raise forms.ValidationError('Mobile Number must be a Integer')
        return mobile

    # validating the password
    def clean_password(self):
        password = self.cleaned_data.get('password')
        upper = lower = num = 0
        for i in password:
            if i.isupper():
                upper += 1
            elif i.islower():
                lower += 1
            elif i.isnumeric():
                num += 1
        if not len(password) >= 8:
            raise forms.ValidationError(
                'Your password must be atleast 8 characters')
        if not upper:
            raise forms.ValidationError(
                'Your password must have atleast 1 UPPERCASE')
        if not lower:
            raise forms.ValidationError(
                'Your password must have atleast 1 lowercase')
        if not num:
            raise forms.ValidationError(
                'Your password must have atleast 1 Numeric [0-9]')
        return password

    # validating the confirm password field
    def clean_confirm_password(self):
        confirm = self.cleaned_data.get('confirm_password')
        if not confirm == self.cleaned_data.get('password'):
            raise forms.ValidationError('Your password does not match')
        return confirm


class SigninForm(forms.Form):
    mobile = forms.CharField(widget=forms.NumberInput(
        attrs={'placeholder': 'Enter your Mobile Number'}
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Must be at least 8+ charaters'}
    ))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['mobile'].label = "Mobile Number"

    # validating the mobile no
    def clean_mobile(self):
        mobile = self.cleaned_data.get('mobile')
        if not len(mobile) == 10:
            raise forms.ValidationError('Enter a valid Mobile Number')
        if not mobile.isnumeric():
            raise forms.ValidationError('Mobile Number must be a Integer')
        return mobile


class MyaccountForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Last Name'}))
    mobile = forms.CharField(widget=forms.NumberInput(
        attrs={'placeholder': 'Enter your Mobile Number'}))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'placeholder': 'yourname@example.com'}))
    address = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Address..'}))
    street = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Street..'}))
    city = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'City...'}))
    state = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'State...'}))
    pincode = forms.CharField(widget=forms.NumberInput(
        attrs={'placeholder': 'Pincode...'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'mobile', 'email', 'gender',
                  'address', 'street', 'city', 'state', 'pincode', 'profile_pic']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['mobile'].label = "Mobile Number"
        self.fields['email'].label = "Email Address"
        self.fields['first_name'].label = "First Name"
        self.fields['last_name'].label = "Last Name"
        self.fields['profile_pic'].label = "Select your Profile picture :"
        self.fields['address'].label = "Address"
        self.fields['street'].label = "Street"
        self.fields['city'].label = "City"
        self.fields['state'].label = "State"
        self.fields['pincode'].label = "Pincode"
        self.fields['last_name'].required = False

    # validating the email
    def clean_email(self):
        email = self.cleaned_data.get('email').lower()
        return email

    # validating the mobile no
    def clean_mobile(self):
        mobile = self.cleaned_data.get('mobile')
        if not len(mobile) == 10:
            raise forms.ValidationError('Enter a valid Mobile Number')
        return mobile

Launderland/usermodule/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required

from .decorators import *
from .models import *
from .forms import *


def customer_signup(request):
    form = SignupForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        user_obj = form.save(commit=False)
        user_obj.password = make_password(user_obj.password)
        user_obj.user_type = 3
        user_obj.save()
        return redirect('usermodule:signin')
    return render(request, 'usermodule/signup.html', {'form': form})


# Common signin for all account
def account_signin(request):
    if request.user.is_authenticated:
        return redirect('homepage')
    form = SigninForm(request.POST or None)
    if form.is_valid():
        mobile = form.cleaned_data.get('mobile')
        password = form.cleaned_data.get('password')
        user = authenticate(request, mobile=mobile, password=password)
        next_link = request.GET.get('next', None)
        if user is not None:
            login(request, user)
            if user.user_type in (1, 2):
                if next_link:
                    return redirect(next_link)
                else:
                    if user.user_type == 1:
                        messages.success(request, "Signed In as Owner (Admin)")
                    elif user.user_type == 2:
                        messages.success(request, "Signed In as Staff")
                    return redirect('homepage')
            if user.user_type == 3:
                if next_link:
                    return redirect(next_link)
                else:
                    messages.success(request, "Signed In as Customer")
                    return redirect('homepage')
        else:
            messages.error(request, "Invalid Mobile number or Password!!!")
    return render(request, 'usermodule/signin.html', {'form': form})


@login_required
def account_signout(request):
    logout(request)
    messages.error(request, "Signed out successfully!!!")
    return redirect('homepage')


@user_is_owner
def staff_signup(request):
    form = SignupForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        user_obj = form.save(commit=False)
        user_obj.password = make_password(user_obj.password)
        user_obj.user_type = 2
        user_obj.save()
        return redirect('homepage')
    return render(request, 'staffmodule/staff_signup.html', {'form': form})


# Common account detail
@login_required
def account_profile(request):
    instance = User.objects.get(id=request.user.id)
    form = MyaccountForm(request.POST or None,
                         request.FILES or None, instance=instance)
    if form.is_valid():
        form.save()
        messages.success(request, "Account updated successfully!")
        return redirect('usermodule:myaccount')
    return render(request, 'usermodule/myaccount.html', {'form': form})

Launderland/templates/usermodule/myaccount.html
{% extends 'base_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
<title>Launder land | Account</title>
{% endblock %}

{% block content %}

<body id="accounts">
    <article class="bg_light_orange_2 container-fluid py-2">
        <section class="pr-md-auto pl-md-5 text-center text-md-left">
            <h3 class="brown mb-0 clamp_size_header">Account Details</h3>
        </section>
    </article>
    <div class="container py-3">
        <div class="float-right">
            <a href="{% url 'usermodule:change_password' %}"
                class="nav-link brown btn btn-cust bg_orange_1 rounded-pill btn-sm bold">Change
                Password <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <article class="container mt-5 px-sm-1">
        <div class="card brown d-flex justify-content-center align-items-center bg-transparent border-0">
            <div class="card-body bg_light_orange_2 rounded mb-3">
                <form method="POST" enctype="multipart/form-data" class="needs-validation" novalidate>
                    <!-- * Showcase Image -->
                    <div class="d-flex align-items-center justify-content-around mb-4">
                        <img src="{{ user.profile_pic.url }}" class="rounded-circle bg-white text-center" id="img-cust"
                            alt="profile" style="width: 100px; height: 100px; border: 5px solid white" />
                    </div>
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="input-group col-md-12 my-5">
                            <div class="custom-file">
                                {{ form.profile_pic|as_crispy_field }}
                            </div>
                        </div>
                        <div class="form-group bold col-md-12">Personal Details :</div>
                        <div class="form-group col-md-6">
                            {{ form.first_name|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.last_name|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.email|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.mobile|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.gender|as_crispy_field }}
                        </div>
                        <div class="form-group bold col-md-12">Address Details :</div>
                        <div class="form-group col-md-12">
                            {{ form.address|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.street|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.city|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.state|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.pincode|as_crispy_field }}
                        </div>
                    </div>
                    <button type="submit" class="btn bg_orange_1 btn-cust btn-block mb-3 brown rounded-pill bold">
                        Save
                    </button>
                </form>
            </div>
        </div>
    </article>
    <script>
        $(document).ready(function () {
            $("#id_profile_pic").change(function () {
                if (this.files && this.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#img-cust').attr('src', e.target.result);
                    }
                    reader.readAsDataURL(this.files[0]);
                }
            });
        });
    </script>
</body>
{% endblock %}

Launderland/templates/usermodule/signin.html
{% extends 'base_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
<title>Launder land | Sign In</title>
{% endblock %}

{% block content %}

<body id="login_body">
    <article class="bg_light_orange_2 container-fluid py-2">
        <section class="pr-md-auto pl-md-5 text-center text-md-left">
            <h3 class="brown mb-0 clamp_size_header">Sign In</h3>
        </section>
    </article>
    <!-- ? Login + Sign Up Form -->
    <article class="container my-5 px-sm-1">
        <div class="card brown d-flex justify-content-center align-items-center bg-transparent border-0">
            <div class="card-body mx-md-auto col-md-7 bg_light_orange_2 rounded">
                <form method="POST" class="needs-validation" novalidate>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn bg_orange_1 btn-cust btn-block mb-3">
                        Sign In
                    </button>
                </form>
            </div>
        </div>
    </article>
</body>

{% endblock %}

Launderland/templates/usermodule/signup.html
{% extends 'base_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
<title>Launder land | Sign Up</title>
{% endblock %}

{% block content %}

<body id="login_body">
    <article class="bg_light_orange_2 container-fluid py-2">
        <section class="pr-md-auto pl-md-5 text-center text-md-left">
            <h3 class="brown mb-0 clamp_size_header">Sign Up</h3>
        </section>
    </article>
    <!-- ? Sign Up Form -->
    <article class="container mt-5 px-sm-1">
        <div class="card brown d-flex justify-content-center align-items-center bg-transparent border-0">
            <div class="card-body bg_light_orange_2 rounded">
                <form method="POST" enctype="multipart/form-data" class="needs-validation" novalidate>
                    <!-- * Showcase Image -->
                    <div class="d-flex align-items-center justify-content-around mb-5">
                        <img src="{% static 'images/profile.png' %}" class="rounded-circle bg-white text-center"
                            id="img-cust" alt="profile" style="width: 100px; height: 100px; border: 5px solid white" />
                    </div>
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="input-group col-md-12 mb-3">
                            <div class="custom-file">
                                {{ form.profile_pic|as_crispy_field }}
                            </div>
                        </div>
                        <div class="form-group bold col-md-12">Personal Details :</div>
                        <div class="form-group col-md-6">
                            {{ form.first_name|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.last_name|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.email|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.mobile|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.password|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.confirm_password|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.gender|as_crispy_field }}
                        </div>
                        <div class="form-group bold col-md-12">Address Details :</div>
                        <div class="form-group col-md-12">
                            {{ form.address|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.street|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.city|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.state|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.pincode|as_crispy_field }}
                        </div>
                    </div>
                    <button type="submit" class="btn bg_orange_1 btn-cust btn-block mb-3">
                        Register
                    </button>
                </form>
            </div>
        </div>
    </article>

    <script>
        $(document).ready(function () {
            $("#id_profile_pic").change(function () {
                if (this.files && this.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#img-cust').attr('src', e.target.result);
                    }
                    reader.readAsDataURL(this.files[0]);
                }
            });
        });
    </script>
</body>

{% endblock %}