Launderland/Launderland/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

from .views import *


urlpatterns = [
    path('', homepage, name="homepage"),
    path('serveradmin/', admin.site.urls),
    path('accounts/', include('usermodule.urls')),
    path('laundry/', include('laundry.urls')),
    path('staff/', include('staffmodule.urls')),
    path('customer/', include('customermodule.urls')),
    path('change_password_done/', auth_views.PasswordChangeDoneView.as_view(),
         name="password_change_done"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Launderland/laundry/urls.py
from django.urls import path
from .views import *

app_name = 'laundry'

urlpatterns = [
    # * Dashboard
    path('', laundry, name='laundry'),
    # * fetching sub_service from service while booking (ajax)
    path('sub_service/', sub_service, name='sub_service'),
    # * Customer Booking Details
    path('order/', Bookings, name='booking'),
    path('myorders/', Mybookings, name='mybooking'),
    path('myorders/<int:id>/', Booking_details, name='booking_details'),
    # * Customer Payment Details
    path('payments/', payment_list, name='payment'),
    # * Staff Booking Details
    path('staff_all_order/', staff_all_booking, name='staff_all_booking'),
    path('staff_all_order/<int:id>/edit',
         staff_booking_edit, name='staff_booking_edit'),
]

Launderland/staffmodule/urls.py
from django.urls import path
from .views import *

app_name = 'staffmodule'

urlpatterns = [
    #  ? SERVICES
    path('services/', service_view, name="service"),
    path('services/<int:id>/edit/', service_edit, name="service_edit"),
    path('services/<int:id>/delete/', service_delete, name="service_delete"),
    #  ? SUBSERVICES
    path('services/<int:id>/subservices/',
         sub_service_view, name="subservices"),
    path('subservices/<int:id>/edit/',
         sub_service_edit, name="sub_service_edit"),
    path('subservices/<int:id>/delete/',
         sub_service_delete, name="sub_service_delete"),
    #  ? STAFF
    path('list/', staff_list, name="staff_list"),
    path('<int:id>/detail/', staff_details, name="staff_details"),
]

Launderland/staffmodule/models.py
from django.db import models
from django.db.models.deletion import CASCADE


class Service(models.Model):
    service = models.CharField(max_length=50)

    def __str__(self):
        return self.service


class Subservice(models.Model):
    sub_service = models.CharField(max_length=35)
    price = models.FloatField(max_length=5)
    service = models.ForeignKey(Service, on_delete=CASCADE)

    def __str__(self):
        return self.sub_service

Launderland/usermodule/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, mobile, password, **extra_fields):
        if not mobile:
            raise ValueError('The given mobile must be set')
        # mobile = self.mobile
        user = self.model(mobile=mobile, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, mobile, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(mobile, password, **extra_fields)

    def create_superuser(self, mobile, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(mobile, password, **extra_fields)


class User(AbstractUser):
    username = None
    mobile = models.CharField(unique=True, max_length=10)
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=15)
    profile_pic = models.ImageField(default="profile.png", blank=True)
    gender_choice = (('Male', 'Male'), ('Female', 'Female'),
                     ('Other', 'Other'))
    gender = models.CharField(max_length=7, choices=gender_choice)
    user_type_choice = ((1, 'Owner'), (2, 'Staff'), (3, 'Customer'))
    user_type = models.PositiveSmallIntegerField(
        choices=user_type_choice)
    staff_status = models.BooleanField(default=False)
    address = models.CharField(max_length=100)
    street = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    pincode = models.CharField(max_length=6)
    creation_date = models.DateTimeField(auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'mobile'
    REQUIRED_FIELDS = ['first_name', 'user_type']

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.last_name + ", " + self.first_name

Launderland/staffmodule/forms.py
from django import forms
from .models import *


class ServiceForm(forms.ModelForm):
    service = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Service...'}))

    class Meta:
        model = Service
        fields = ['service']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['service'].label = "Services"


class SubServiceForm(forms.ModelForm):
    sub_service = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Sub service...'}))
    price = forms.FloatField(widget=forms.NumberInput())

    class Meta:
        model = Subservice
        fields = ['sub_service', 'price']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['sub_service'].label = "Sub Service"

Launderland/staffmodule/views.py
from usermodule.models import User
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from usermodule.decorators import user_is_staff, user_is_owner
from django.utils.timezone import now, timedelta

from .forms import *
from .models import *


# all user can view service
def service_view(request):
    services = Service.objects.all()
    form = ServiceForm(request.POST or None)
    if form.is_valid():
        if request.user.user_type == 1:
            form.save()
        else:
            messages.warning(
                request, 'Staff cannot add a new Service. Only Owner can add new service')
    context = {'form': form, 'services': services}
    return render(request, 'staffmodule/service.html', context=context)


@user_is_owner
def service_edit(request, id):
    if request.method == "POST":
        service = request.POST.get('service')
        if Service.objects.filter(id=id).exists():
            demo = Service.objects.filter(service=service) or None
            if demo is None:
                Service.objects.filter(id=id).update(service=service)
                messages.info(request, 'Service edited successfully!!!')
            else:
                messages.info(request, 'No changes detected..')
        else:
            messages.info(request, 'Couldn\'t able to find the service')
        return redirect('staffmodule:service')
    else:
        return redirect('homepage')


@user_is_owner
def service_delete(request, id):
    service = get_object_or_404(Service, id=id)
    service.delete()
    messages.success(request, 'Deleted successfully!!!')
    return redirect('staffmodule:service')


# all user can view Subservice
def sub_service_view(request, id):
    sub_service = Subservice.objects.filter(service=id)
    form = SubServiceForm(request.POST or None)
    if form.is_valid():
        if request.user.user_type == 1:
            form_obj = form.save(commit=False)
            form_obj.service = Service.objects.get(id=id)
            form_obj.save()
        else:
            messages.warning(
                request, 'Staff cannot add a new Service. Only Owner can add new service')
    context = {'form': form, 'sub_service': sub_service}
    return render(request, 'staffmodule/sub_service.html', context=context)


@user_is_owner
def sub_service_edit(request, id):
    if request.method == "POST":
        sub_service = request.POST.get('sub_service')
        price = request.POST.get('price')
        if Subservice.objects.filter(id=id).exists():
            demo = Subservice.objects.filter(
                sub_service=sub_service, id=id) or None
            prices = Subservice.objects.filter(price=price, id=id) or None
            if demo is None or prices is None:
                Subservice.objects.filter(id=id).update(
                    sub_service=sub_service)
                Subservice.objects.filter(id=id).update(price=price)
                messages.info(request, 'Subservice edited successfully!!!')
            else:
                messages.info(request, 'No changes detected..')
        else:
            messages.info(request, 'Couldn\'t able to find the Subservice')

        service = Subservice.objects.get(id=id)
        return redirect('staffmodule:subservices', id=service.service_id)
    else:
        return redirect('homepage')


@user_is_owner
def sub_service_delete(request, id):
    subservice = Subservice.objects.get(id=id)
    subservice.delete()
    messages.success(request, 'Deleted successfully!!!')
    return redirect('staffmodule:subservices', id=subservice.service_id)


@user_is_staff
def staff_list(request):
    staffs = User.objects.filter(user_type=2)
    return render(request, 'staffmodule/staff_list.html', {'staffs': staffs})


@user_is_staff
def staff_details(request, id):
    customer = get_object_or_404(User, id=id)
    status_time = (now() - timedelta(hours=24)
                   ) < (customer.last_login or (now() - timedelta(hours=24)))
    staff = get_object_or_404(User, id=id)
    context = {'staff': staff, 'status_time': status_time}
    return render(request, 'staffmodule/staff_detail.html', context)

Launderland/templates/staffmodule/service.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
<title>Launder land | Services</title>
{% endblock %}

{% block content %}

<body id="staff">
    <!-- ? Service Title -->
    <article class="bg_light_orange_2 container-fluid py-2">
        <section class="pr-md-auto pl-md-5 text-center text-md-left">
            <h3 class="brown mb-0 clamp_size_header">Services</h3>
        </section>
    </article>
    <!-- ? List of Services -->
    <article class="container my-2">
        {% if user.user_type == 1 %}
        <!-- Modal -->
        <article class="modal fade" id="add_service_modal" data-backdrop="static" data-keyboard="false" tabindex="-1"
            role="dialog" aria-labelledby="staticBackdropLabel" aria-modal="true">
            <div class="modal-dialog d-flex justfy-content-center align-items-center" style="height: 90vh;">
                <div class="modal-content">
                    <section class="modal-header bg_light_orange_2 brown">
                        <h5 class="modal-title" id="exampleModalLabel">Add a Service</h5>
                        <button type="button" class="btn btn-cust close" data-dismiss="modal" aria-label="Close">×
                        </button>
                    </section>
                    <!-- Add Service Form -->
                    <section class="modal-body bg_light_orange_1">
                        <form id="add_form" method="POST" role="form" class="brown">
                            {% csrf_token %}
                            {{ form|crispy }}
                        </form>
                    </section>
                    <!-- Add Service Button -->
                    <section class="modal-footer brown bg_light_orange_2">
                        <button type="cancel" class="btn btn-cust btn-warning bold" data-dismiss="modal">Cancel</button>
                        <input type="submit" name="submit" value="Add" form="add_form"
                            class="btn btn-cust btn-success bold">
                    </section>
                </div>
            </div>
        </article>
        <!-- Add modal toggle button -->
        <button type="button" class="btn-cust bg_light_orange_1 brown btn float-right my-2" id="add_service"
            data-toggle="modal" data-target="#add_service_modal">Add <i class="fas fa-plus brown"></i>
        </button>
        {% endif %}
        <section class="card shadow-sm my-3 w-100">
            <div class="card-body p-0">
                <div class="table-responsive table-wrapper">
                    <table class="table table-striped table-hover mb-0 brown">
                        <!-- * Table Header -->
                        <thead class="bg_light_orange_2">
                            <tr>
                                <th scope="col">No.</th>
                                <th scope="col">Services</th>
                                <th scope="col">Sub Services</th>
                                {% if user.user_type == 1 %}
                                <th scope="col"></th>
                                {% endif %}
                            </tr>
                        </thead>
                        <!-- * Table Content -->
                        <tbody>
                            {% for data in services %}
                            <tr>
                                {% if forloop %}
                                <th>{{forloop.counter}}</th>
                                {% endif %}
                                {% if user.user_type == 1 %}
                                <td>
                                    <form id="edit_form{{ data.id }}" method="POST"
                                        action="{% url 'staffmodule:service_edit' data.id %}">
                                        {% csrf_token %}
                                        <input type="text" name="service" class="form-control"
                                            value="{{ data.service }}">
                                    </form>
                                </td>
                                <td>
                                    <a class="nav-link p-0" href="{% url 'staffmodule:subservices' data.id %}">
                                        Subservice of {{ data.service }}
                                    </a>
                                </td>
                                <td class="text-right">
                                    <input type="submit" form="edit_form{{ data.id }}" value="Save"
                                        class="btn btn-cust blue bold">
                                    <input type="button" name="submit" value="Delete" class="btn btn-cust red bold"
                                        data-toggle="modal" data-target="#del{{ data.id }}">
                                </td>
                                {% else %}
                                <td>{{ data.service }}</td>
                                <td>
                                    <a class="nav-link p-0" href="{% url 'staffmodule:subservices' data.id %}">
                                        Subservice of {{ data.service }}
                                    </a>
                                </td>
                                {% endif %}
                            </tr>
                            {% if user.user_type == 1 %}
                            <div class="modal fade" id="del{{ data.id }}" data-backdrop="static" data-keyboard="false"
                                tabindex="-1">
                                <!-- Delete A Service  -->
                                <div class="modal-dialog d-flex justfy-content-center align-items-center"
                                    style="height: 90vh;">
                                    <div class="modal-content brown">
                                        <section class="modal-header bg_light_orange_1">
                                            <h4 class="modal-title bold">Confirmation</h4>
                                            <button type="button" class="btn-cust close"
                                                data-dismiss="modal">&times;</button>
                                        </section>
                                        <section class="modal-body">
                                            <h4 class="modal-title">Are you sure you want to delete?</h4>
                                            <h5 class="bold my-2">{{ data.service }}</h5>
                                        </section>
                                        <section class="modal-footer bg_light_orange_1">
                                            <a href="{% url 'staffmodule:service_delete' data.id %}"
                                                class="btn btn-cust red">Yes,&nbsp;Delete</a>
                                            <button type="button" class="btn btn-cust btn-warning"
                                                data-dismiss="modal">Cancel</button>
                                        </section>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </article>

    <script>
        $(document).ready(function () {
            $("#add_service").click(function () {
                $("#add_service_modal").modal("show");
            })
        });
    </script>
</body>

{% endblock %}

Launderland/templates/staffmodule/staff_list.html
{% extends 'base_layout.html' %}
{% load static %}

{% block title %}
<title>Launder land | Staff List</title>
{% endblock %}

{% block content %}

<body id="staff_stuffs">
    <!-- ? Staff List Title -->
    <article class="bg_light_orange_2 container-fluid py-2">
        <section class="pr-md-auto pl-md-5 text-center text-md-left">
            <h3 class="brown mb-0 clamp_size_header">Staffs</h3>
        </section>
    </article>
    <article class="container-fluid my-2">
        {% if staffs %}
        <div class="row d-flex justify-content-center">
            {% for staff in staffs %}
            <section class="card card-cust bg-transparent border-0 m-2" style="width: 18rem;">
                <div class="mx-auto img_body d-flex">
                    <img src="{{ staff.profile_pic.url }}" class="rounded-circle mb-n5" width="95"
                        alt="{{ staff.first_name }} image" style="z-index:500">
                </div>
                <div class="card-body bg_light_orange_1 text-center brown rounded">
                    <h5 class="card-title pt-5">{{ staff.first_name }}</h5>
                    <h5 class="card-title">{{ staff.email }}</h5>
                    <h5 class="card-title">{{ staff.mobile }}</h5>
                    <a href="{% url 'staffmodule:staff_details' staff.id %}"
                        class="btn btn-cust bg_orange_1 rounded-pill brown bold">View
                        Details</a>
                </div>
            </section>
            {% endfor %}
            {% else %}
            <div class="row d-flex justify-content-center align-items-center" style="height: 50vh;">
                <h4 class="bold brown"> No Staffs to View</h4>
                {% endif %}
            </div>
    </article>
</body>

{% endblock %}

Launderland/templates/staffmodule/staff_signup.html
{% extends 'base_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
<title>Launder land | Owner | Create Staff Account</title>
{% endblock %}

{% block content %}

<body id="staff">
    <!-- ? Title -->
    <article class="bg_light_orange_2 container-fluid py-2">
        <section class="pr-md-auto pl-md-5 text-center text-md-left">
            <h3 class="brown mb-0 clamp_size_header">Create a Staff Account</h3>
        </section>
    </article>
    <!-- ? Staff Sign Up Form -->
    <article class="container my-5 px-sm-1">
        <div class="card brown d-flex justify-content-center align-items-center bg-transparent border-0">
            <div class="card-body bg_light_orange_2 rounded">
                <form method="POST" enctype="multipart/form-data" class="needs-validation" novalidate>
                    <!-- * Showcase Image -->
                    <div class="d-flex align-items-center justify-content-around mb-5">
                        <img src="{% static 'images/profile.png' %}" class="rounded-circle bg-white text-center"
                            id="img-cust" alt="profile" style="width: 100px; height: 100px; border: 5px solid white" />
                    </div>
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="input-group col-md-12 mb-3">
                            <div class="custom-file">
                                {{ form.profile_pic|as_crispy_field }}
                            </div>
                        </div>
                        <div class="form-group bold col-md-12">Personal Details :</div>
                        <div class="form-group col-md-6">
                            {{ form.first_name|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.last_name|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.email|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.mobile|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.password|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.confirm_password|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.gender|as_crispy_field }}
                        </div>
                        <div class="form-group bold col-md-12">Address Details :</div>
                        <div class="form-group col-md-12">
                            {{ form.address|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.street|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.city|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.state|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.pincode|as_crispy_field }}
                        </div>
                    </div>
                    <button type="submit" class="btn bg_orange_1 btn-cust btn-block mb-3">
                        Register
                    </button>
                </form>
            </div>
        </div>
    </article>

    <script>
        $(document).ready(function () {
            $("#id_profile_pic").change(function () {
                if (this.files && this.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#img-cust').attr('src', e.target.result);
                    }
                    reader.readAsDataURL(this.files[0]);
                }
            });
        });
    </script>
</body>

{% endblock %}

Launderland/templates/staffmodule/sub_service.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
<title>Launder land | Sub Services</title>
{% endblock %}

{% block content %}

<body id="staff">
    <!-- ? Sub Service Title -->
    <article class="bg_light_orange_2 container-fluid py-2">
        <section class="pr-md-auto pl-md-5 text-center text-md-left">
            {% for data in sub_service %}
            {% if forloop.first %}
            <h3 class="brown mb-0 clamp_size_header">Sub service of {{ data.service }}</h3>
            {% endif %}
            {% endfor %}
        </section>
    </article>
    <!-- ? List of Sub services -->
    <article class="container my-2">
        {% if user.user_type == 1 %}
        <!-- Modal -->
        <article class="modal fade" id="add_sub_service_modal" data-backdrop="static" data-keyboard="false"
            tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-modal="true">
            <div class="modal-dialog d-flex justfy-content-center align-items-center" style="height: 90vh;">
                <div class="modal-content">
                    <section class="modal-header bg_light_orange_2 brown">
                        <h5 class="modal-title" id="exampleModalLabel">Add a Subservice</h5>
                        <button type="button" class="btn btn-cust close" data-dismiss="modal" aria-label="Close">×
                        </button>
                    </section>
                    <!-- Add Subservice Form -->
                    <section class="modal-body bg_light_orange_1">
                        <form id="add_form" method="POST" role="form" class="brown">
                            {% csrf_token %}
                            {{ form|crispy }}
                        </form>
                    </section>
                    <!-- Add Subservice Button -->
                    <section class="modal-footer brown bg_light_orange_2">
                        <button type="cancel" class="btn btn-cust btn-warning bold" data-dismiss="modal">Cancel</button>
                        <input type="submit" name="submit" value="Add" form="add_form"
                            class="btn btn-cust btn-success bold">
                    </section>
                </div>
            </div>
        </article>
        <!-- Add modal toggle button -->
        <button type="button" class="btn-cust bg_light_orange_1 brown btn float-right my-2" id="add_sub_service"
            data-toggle="modal" data-target="#add_sub_service_modal">Add <i class="fas fa-plus brown"></i>
        </button>
        {% endif %}
        <section class="card shadow-sm my-3 w-100">
            <div class="card-body p-0">
                <div class="table-responsive table-wrapper">
                    <table class="table table-striped table-hover mb-0 brown">
                        <!-- * Table Header -->
                        <thead class="bg_light_orange_2">
                            <tr>
                                <th scope="col">No.</th>
                                <th scope="col">Subservices</th>
                                <th scope="col">Price</th>
                                {% if user.user_type == 1 %}
                                <th scope="col"></th>
                                {% endif %}
                            </tr>
                        </thead>
                        <!-- * Table Content -->
                        <tbody>
                            {% for data in sub_service %}
                            <tr>
                                {% if forloop %}
                                <th>{{forloop.counter}}</th>
                                {% endif %}
                                {% if user.user_type == 1 %}
                                <form id="edit_form{{ data.id }}" method="POST"
                                    action="{% url 'staffmodule:sub_service_edit' data.id %}">
                                    {% csrf_token %}
                                    <td>
                                        <input type="text" name="sub_service" class="form-control"
                                            value="{{ data.sub_service }}">
                                    </td>
                                    <td>
                                        <input type="text" name="price" class="form-control" value="{{ data.price }}">
                                    </td>
                                </form>
                                <td class="text-right">
                                    <input type="submit" form="edit_form{{ data.id }}" value="Save"
                                        class="btn btn-cust blue bold">
                                    <input type="button" name="submit" value="Delete" class="btn btn-cust red bold"
                                        data-toggle="modal" data-target="#del{{ data.id }}">
                                </td>
                                {% else %}
                                <td>{{ data.sub_service }}</td>
                                <td>{{ data.price }}</td>
                                {% endif %}
                            </tr>
                            {% if user.user_type == 1 %}
                            <div class="modal fade" id="del{{ data.id }}" data-backdrop="static" data-keyboard="false"
                                tabindex="-1">
                                <!-- Delete A Sub service  -->
                                <div class="modal-dialog d-flex justfy-content-center align-items-center"
                                    style="height: 90vh;">
                                    <div class="modal-content brown">
                                        <section class="modal-header bg_light_orange_1">
                                            <h4 class="modal-title bold">Confirmation</h4>
                                            <button type="button" class="btn-cust close"
                                                data-dismiss="modal">&times;</button>
                                        </section>
                                        <section class="modal-body">
                                            <h4 class="modal-title">Are you sure you want to delete?</h4>
                                            <h5 class="bold my-2">{{ data.sub_service }}</h5>
                                        </section>
                                        <section class="modal-footer bg_light_orange_1">
                                            <a href="{% url 'staffmodule:sub_service_delete' data.id %}"
                                                class="btn btn-cust red">Yes,&nbsp;Delete</a>
                                            <button type="button" class="btn btn-cust btn-warning"
                                                data-dismiss="modal">Cancel</button>
                                        </section>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </article>

    <script>
        $(document).ready(function () {
            $("#add_sub_service").click(function () {
                $("#add_sub_service_modal").modal("show");
            })
        });
    </script>
</body>

{% endblock %}