Launderland/Launderland/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

from .views import *


urlpatterns = [
    path('', homepage, name="homepage"),
    path('serveradmin/', admin.site.urls),
    path('accounts/', include('usermodule.urls')),
    path('laundry/', include('laundry.urls')),
    path('staff/', include('staffmodule.urls')),
    path('customer/', include('customermodule.urls')),
    path('change_password_done/', auth_views.PasswordChangeDoneView.as_view(),
         name="password_change_done"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Launderland/laundry/urls.py
from django.urls import path
from .views import *

app_name = 'laundry'

urlpatterns = [
    # * Dashboard
    path('', laundry, name='laundry'),
    # * fetching sub_service from service while booking (ajax)
    path('sub_service/', sub_service, name='sub_service'),
    # * Customer Booking Details
    path('order/', Bookings, name='booking'),
    path('myorders/', Mybookings, name='mybooking'),
    path('myorders/<int:id>/', Booking_details, name='booking_details'),
    # * Customer Payment Details
    path('payments/', payment_list, name='payment'),
    # * Staff Booking Details
    path('staff_all_order/', staff_all_booking, name='staff_all_booking'),
    path('staff_all_order/<int:id>/edit',
         staff_booking_edit, name='staff_booking_edit'),
]

Launderland/usermodule/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'usermodule'

urlpatterns = [
    path('signup/', customer_signup, name='signup'),
    path('signin/', account_signin, name='signin'),
    path('signout/', account_signout, name='signout'),
    path('myaccount/', account_profile, name='myaccount'),
    path('staff/signup/', staff_signup, name='signup_staff'),
    path('change_password/', auth_views.PasswordChangeView.as_view(),
         name="change_password"),
]

Launderland/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %} {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" />
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Bootstrap JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
        integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous" />
    <!-- Font : QuickSans -->
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500&display=swap" rel="stylesheet" />
    <!-- Animate css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css" />
    <!-- Website Icon -->
    <link rel="icon" href="{% static 'images/logo.png' %}" />
    <!-- Custom Css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>


<body>

    <header>
        {% include 'messages.html' %}
        <!-- Header -->
        {% include 'header.html' %}
    </header>
    <main>
        <!-- Main Content -->
        {% block content %} {% endblock %}
    </main>
    <footer class="pt-4 mt-5 pt-md-5 border-top bg_orange_1 ">
        <!-- Footer -->
        {% include 'footer.html' %}
    </footer>
</body>

</html>

Launderland/templates/footer.html
{% load static %}

<div class="row mx-0 text-center">
    <div class="col-12 col-md">
        <img class="mb-2" src="{% static 'images/logo.png' %}" alt="" width="24" height="24">
        <small class="d-block mb-3 brown">© 2015-2020</small>
    </div>
    <div class="col-12 col-md">
        <h5 class="bold">Features</h5>
        <ul class="list-unstyled text-small brown">
            <li><a class="text-muted nav-link brown" href="#">Detailed inspection</a></li>
            <li><a class="text-muted nav-link brown" href="#">
                    Premium cleaning</a></li>
            <li><a class="text-muted nav-link brown" href="#">
                    Your preferences</a></li>
            <li><a class="text-muted nav-link brown" href="#">Expert care</a></li>
            <li><a class="text-muted nav-link brown" href="#">Pressed and hung</a></li>
        </ul>
    </div>
    <div class="col-12 col-md">
        <h5 class="bold">Connect</h5>
        <ul class="list-unstyled text-small brown">
            <li><a class="text-muted nav-link brown" href="#">Blog</a></li>
            <li><a class="text-muted nav-link brown" href="#">Facebook</a></li>
            <li><a class="text-muted nav-link brown" href="#">Instagram</a></li>
            <li><a class="text-muted nav-link brown" href="#">Twitter</a></li>
        </ul>
    </div>
    <div class="col-12 col-md">
        <h5 class="bold">Company</h5>
        <ul class="list-unstyled text-small brown">
            <li><a class="text-muted nav-link brown" href="#">About</a></li>
            <li><a class="text-muted nav-link brown" href="#">Contact</a></li>
            <li><a class="text-muted nav-link brown" href="#">FAQs</a></li>
            <li><a class="text-muted nav-link brown" href="#">Terms</a></li>
        </ul>
    </div>
</div>

Launderland/templates/header.html
{% load static %}
{% url 'homepage' as home %}
{% url 'usermodule:signout' as signout %}
{% url 'usermodule:signin' as signin %}
{% url 'usermodule:signup' as signup %}
{% url 'usermodule:myaccount' as myaccount %}
{% url 'laundry:laundry' as laundry %}

<div>
    <!-- ? Logo Navbar -->
    <nav class="navbar navbar-expand-lg bg_orange_1">
        <div class="container mx_width_100 justify-content-between">
            <!-- * Brand Logo -->
            <a class="navbar-brand flex-shrink-0 btn-cust d-flex" href="{% url 'homepage' %}"
                style="min-width: 7rem"><img src="{% static 'images/logo.png' %}" alt="Horbax" width="45" />
                <h6 class="my-auto ml-2 brown bold">Launder land</h6>
            </a>
            <div class="container order-1 order-lg-0">
                <div class="navbar-collapse collapse d-lg-flex justify-content-center align-items-center"
                    id="navbarCollapse">
                    <!-- * Primary menu-->
                    <ul class="navbar-nav">
                        <li class="nav-item my-2 mx-lg-3 clamp_size">
                            <a class="{% if request.get_full_path == home %}actives{% else %}brown{% endif %} nav-link border-0 btn-cust text-center header_big"
                                href="{% url 'homepage' %}">Home</a>
                        </li>
                        <li class="nav-item my-2 mx-lg-3 clamp_size">
                            <a class="{% if request.get_full_path == laundry %}actives{% else %}brown{% endif %} nav-link header_big border-0 btn-cust text-center"
                                href="{% url 'laundry:laundry' %}">Laundry</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item my-2 mx-lg-3 clamp_size">
                            <a class="{% if request.get_full_path == myaccount %}actives{% else %}brown{% endif %} nav-link header_big border-0 btn-cust text-center"
                                href="{% url 'usermodule:myaccount' %}">Account</a>
                        </li>
                        <li class="nav-item my-2 mx-lg-3 clamp_size d-md-none">
                            <a class="brown nav-link header_big border-0 btn-cust text-center"
                                href="{% url 'usermodule:signout' %}">Sign&nbsp;Out</a>
                        </li>
                        {% else %}
                        <li class="nav-item my-2 mx-lg-3 clamp_size d-md-none">
                            <a class="{% if request.get_full_path == signin %}actives{% else %}brown{% endif %} nav-link header_big border-0 btn-cust text-center"
                                href="{% url 'usermodule:signin' %}">Sign&nbsp;In</a>
                        </li>
                        <li class="nav-item my-2 mx-lg-3 clamp_size d-md-none">
                            <a class="{% if request.get_full_path == signup %}actives{% else %}brown{% endif %} nav-link header_big border-0 btn-cust text-center"
                                href="{% url 'usermodule:signup' %}">Sign&nbsp;Up</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <!-- Right Side -->
            <div class="navbar-toolbar d-flex flex-shrink-0 align-items-center order-0 orderlg-1">
                {% if user.is_authenticated %}
                <!-- * My Account -->
                <div class="nav-item dropdown d-flex order-md-2">
                    <a class="navbar-tool mx-sm-1 mx-md-0 text-decoration-none btn-cust"
                        href="{% url 'usermodule:myaccount' %}">
                        <div class="navbar-tool-icon-box">
                            <img class="rounded-circle" src="{{ user.profile_pic.url }}" width="35"
                                style="border: 2px solid white" alt="Profile" />
                        </div>
                    </a>
                    <a class="nav-link dropdown-toggle btn-cust d-none d-md-block px-1 mr-lg-4
              {% if request.get_full_path == profile %}active{% else %}brown{% endif %}" href="#" id="navbardrop"
                        data-toggle="dropdown">
                        {{ user.first_name }}
                    </a>
                    <div class="dropdown-menu bg_light_orange_1">
                        <a href="{% url 'usermodule:myaccount' %}" class="dropdown-item">
                            <i class="fas fa-user"></i>&nbsp;My&nbsp;Account
                        </a>
                        <a href="{% url 'usermodule:signout' %}" class="dropdown-item">
                            <i class="fas fa-sign-out-alt"></i>&nbsp;Sign&nbsp;Out
                        </a>
                    </div>
                </div>
                {% else %}
                <div class="navbar-tool btn-cust d-none d-md-block">
                    <a class="{% if request.get_full_path == signin %}actives{% else %}brown{% endif %} nav-link border-0 btn-cust"
                        href="{% url 'usermodule:signin' %}">Sign&nbsp;In</a>
                </div>
                <div class="navbar-tool btn-cust d-none d-md-block">
                    <a class="{% if request.get_full_path == signup %}actives{% else %}brown{% endif %} nav-link border-0 btn-cust"
                        href="{% url 'usermodule:signup' %}">Sign&nbsp;Up</a>
                </div>
                {% endif %}
                <!-- * Hamburger Button-->
                <button class="navbar-toggler collapsed btn btn-cust order-md-3" type="button" data-toggle="collapse"
                    data-target="#navbarCollapse" aria-expanded="false">
                    <i class="fas fa-bars fa-lg brown"></i>
                </button>
            </div>
        </div>
    </nav>
    <!-- ? Navbar Menus -->
    <!-- <nav class="navbar navbar-expand-lg navbar-stuck-menu mt-n2 pt-0 pb-2 px-0 bg_orange_1">

    </nav> -->
</div>

Launderland/templates/index.html
{% extends 'base_layout.html' %}
{% load static %}

{% block title %}
<title>Launder land</title>
{% endblock %}

{% block content %}

<body id="home_body">
    <section class="p-3">
        <div class="row d-flex justify-content-center align-items-center" style="height: 90vh;">
            <div class="col-xl-8 col-lg-9 col-md-10 col-sm-8 text-left brown">
                <h1 class="bold">
                    Your Dry Cleaning<br>and Laundry. Done.
                </h1>
                <div class="mb-4">
                    <p class="lead">
                        Launder land picks up, cleans & delivers.<br>
                        Now you have time for what really matters.
                    </p>
                </div>
                <a href="{% url 'laundry:laundry' %}"
                    class="btn btn-lg btn-white mx-1 bg_light_orange_1 brown rounded-pill bold">Dashboard</a>
                {% if user.user_type == 1 or user.user_type == 2 %}
                <a href="{% url 'laundry:staff_all_booking' %}"
                    class="btn btn-lg btn-cust bg_orange_1 mx-1 light_orange_1 rounded-pill bold">Check Orders</a>
                {% else %}
                <a href="{% url 'laundry:booking' %}"
                    class="btn btn-lg btn-cust bg_orange_1 mx-1 light_orange_1 rounded-pill bold">Order Now</a>
                {% endif %}
            </div>
        </div>
    </section>
</body>

{% endblock %}

Launderland/templates/messages.html
{% load static %}

<div aria-live="polite" aria-atomic="true" style="position: relative; z-index:1800">
    {% for message in messages %}
    <div class="toast mr-md-3 mt-md-3" style="position: absolute; top: 0; right: 0;" data-delay="1500"
        id="{{ forloop.counter0 }}">
        <div class="toast-header bg_orange_1 brown">
            <img src="{% static 'images/logo.png' %}" width="35" class="rounded-circle mr-2" alt="Horbax">
            <strong class="mr-auto">Notification</strong>
            <small>Just Now</small>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body bg_light_orange_1">
            <h5 class="{{ message.tags }} brown">{{ message }}</h5>
        </div>
    </div>
    {% endfor %}
</div>

<script type="text/javascript">
    $(document).ready(function () {
        {% for message in messages %}
        $('#{{ forloop.counter0 }}').toast('show');
        {% endfor %}
    });
</script>